CREATE TABLE vehicle_tracking.route_shape_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES vehicle_tracking.routes(id) ON DELETE CASCADE,
    point_order INTEGER NOT NULL CHECK (point_order >= 1),
    destination_stop_sequence INTEGER NOT NULL CHECK (destination_stop_sequence >= 2),
    latitude NUMERIC(8,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    UNIQUE(route_id, point_order)
);
ALTER TABLE vehicle_tracking.trip_route_revisions
    ADD COLUMN simulation_start_elapsed DOUBLE PRECISION,
    ADD COLUMN simulation_attempt_number INTEGER;
ALTER TABLE vehicle_tracking.trip_route_revisions ADD CONSTRAINT simulation_revision_application_valid CHECK (
    (simulation_start_elapsed IS NULL AND simulation_attempt_number IS NULL) OR
    (simulation_start_elapsed IS NOT NULL AND simulation_attempt_number IS NOT NULL
     AND simulation_start_elapsed >= 0 AND simulation_start_elapsed < 'Infinity'::float8
     AND simulation_attempt_number >= 1)
);
