CREATE TABLE vehicle_tracking.operating_depot (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    name VARCHAR(100) NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    address VARCHAR(255) NOT NULL CHECK (length(btrim(address)) BETWEEN 1 AND 255),
    revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by_account_id BIGINT NOT NULL REFERENCES vehicle_tracking.user_accounts(id) ON DELETE RESTRICT
);

CREATE TABLE vehicle_tracking.depot_return_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES vehicle_tracking.trips(id) ON DELETE RESTRICT,
    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
    depot_id SMALLINT NOT NULL REFERENCES vehicle_tracking.operating_depot(id) ON DELETE RESTRICT,
    depot_revision BIGINT NOT NULL CHECK (depot_revision >= 0),
    depot_name_snapshot VARCHAR(100) NOT NULL CHECK (length(btrim(depot_name_snapshot)) BETWEEN 1 AND 100),
    depot_address_snapshot VARCHAR(255) NOT NULL CHECK (length(btrim(depot_address_snapshot)) BETWEEN 1 AND 255),
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('PLANNED', 'NOT_REQUIRED', 'RETURNED')),
    planned_return_at TIMESTAMPTZ,
    reason VARCHAR(500),
    note VARCHAR(500) CHECK (note IS NULL OR length(btrim(note)) BETWEEN 1 AND 500),
    confirmed_vehicle_id BIGINT REFERENCES vehicle_tracking.vehicles(id) ON DELETE RESTRICT,
    vehicle_plate_snapshot VARCHAR(20),
    confirmed_driver_id BIGINT REFERENCES vehicle_tracking.drivers(id) ON DELETE RESTRICT,
    driver_name_snapshot VARCHAR(100),
    returned_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    confirmed_by_account_id BIGINT REFERENCES vehicle_tracking.user_accounts(id) ON DELETE RESTRICT,
    source VARCHAR(20) CHECK (source IS NULL OR source = 'ADMIN_MANUAL'),
    revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by_account_id BIGINT NOT NULL REFERENCES vehicle_tracking.user_accounts(id) ON DELETE RESTRICT,
    CONSTRAINT uq_depot_return_trip_attempt UNIQUE (trip_id, attempt_number),
    CONSTRAINT ck_depot_return_state CHECK (
        (mode = 'PLANNED' AND planned_return_at IS NOT NULL AND reason IS NULL
            AND returned_at IS NULL AND confirmed_at IS NULL AND confirmed_by_account_id IS NULL
            AND source IS NULL AND confirmed_vehicle_id IS NULL AND vehicle_plate_snapshot IS NULL
            AND confirmed_driver_id IS NULL AND driver_name_snapshot IS NULL)
        OR (mode = 'NOT_REQUIRED' AND planned_return_at IS NULL
            AND reason IS NOT NULL AND length(btrim(reason)) BETWEEN 3 AND 500
            AND returned_at IS NULL AND confirmed_at IS NULL AND confirmed_by_account_id IS NULL
            AND source IS NULL AND confirmed_vehicle_id IS NULL AND vehicle_plate_snapshot IS NULL
            AND confirmed_driver_id IS NULL AND driver_name_snapshot IS NULL)
        OR (mode = 'RETURNED' AND reason IS NULL AND returned_at IS NOT NULL
            AND confirmed_at IS NOT NULL AND returned_at <= confirmed_at
            AND confirmed_by_account_id IS NOT NULL AND source IS NOT NULL AND source = 'ADMIN_MANUAL'
            AND confirmed_vehicle_id IS NOT NULL AND vehicle_plate_snapshot IS NOT NULL
            AND length(btrim(vehicle_plate_snapshot)) BETWEEN 1 AND 20
            AND ((confirmed_driver_id IS NULL AND driver_name_snapshot IS NULL)
                OR (confirmed_driver_id IS NOT NULL AND driver_name_snapshot IS NOT NULL
                    AND length(btrim(driver_name_snapshot)) BETWEEN 1 AND 100)))
    )
);

CREATE INDEX idx_depot_return_planned_at ON vehicle_tracking.depot_return_records(planned_return_at, trip_id)
    WHERE mode = 'PLANNED';
CREATE INDEX idx_depot_return_returned_at ON vehicle_tracking.depot_return_records(returned_at, trip_id)
    WHERE mode = 'RETURNED';
