package com.quangkhai.vehicletracking_backend.trip.dto;

/** Distinguishes manually dispatched trips from occurrences generated by a fixed schedule. */
public enum TripDispatchMode {
    ON_DEMAND,
    FIXED_SCHEDULE
}
