package com.quangkhai.vehicletracking_backend.traffic;

public enum TrafficErrorCode {
    TRAFFIC_BOUNDS_INVALID,
    TRAFFIC_UNAVAILABLE,
    TRAFFIC_PROVIDER_UNAVAILABLE,
    TRAFFIC_PROVIDER_TIMEOUT,
    TRAFFIC_PROVIDER_INVALID_RESPONSE,
    TRAFFIC_PROVIDER_UNAUTHORIZED,
    TRIP_NOT_FOUND,
    ETA_UNAVAILABLE
}
