package com.quangkhai.vehicletracking_backend.route.error;

public enum RouteErrorCode {
    ROUTE_VALIDATION_FAILED,
    ROUTE_STATION_UNAVAILABLE,
    ROUTE_NOT_FOUND_BY_PROVIDER,
    ROUTE_NOT_FOUND,
    ROUTING_UNAVAILABLE,
    ROUTING_PROVIDER_UNAVAILABLE,
    ROUTING_PROVIDER_TIMEOUT,
    ROUTING_PROVIDER_INVALID_RESPONSE
}
