package com.quangkhai.vehicletracking_backend.dispatch.entity;

public enum DispatchEventKind {
    CREATED, POLICY_CHANGED, READY, BUSY, SEARCH_OPENED, OFFERED, OFFER_DECLINED,
    OFFER_EXPIRED, OFFER_CANCELLED, REASSIGNED, DUE_ALERTED, AUTO_STARTED,
    OVERRIDE_STARTED, ATTENTION_CHANGED, SCHEDULE_PAUSED, SCHEDULE_RESUMED, CLOSED
}
