package com.quangkhai.vehicletracking_backend.dispatch.entity;

public enum DriverInboxKind {
    TRIP_ASSIGNED, TRIP_UNASSIGNED, READY_WINDOW_OPEN, OFFER_RECEIVED,
    OFFER_CANCELLED, OFFER_EXPIRED, TRIP_STARTED,
    DIRECT_ASSIGNMENT_REQUESTED, DIRECT_ASSIGNMENT_CANCELLED, DIRECT_ASSIGNMENT_ACCEPTED
}
